services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - SQL_DATABASE_URL=postgresql://postgres:postgre@host.docker.internal:5432/flock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
